[[lattices]]
namespace = "kuske"
name = "bessy3_5ba-20p_v_reference"
title = "BESSY 3 Design Kuske 5BA 20p Reference"
machine = "bessy3"
authors = ["Bettina Kuske"]
energy = 2500
simulations = ["apace", "elegant", "madx"]
labels = []
description = """
Referenzl√∂sung (kleines alpha)
"""

[[lattices]]
namespace = "kuske"
name = "bessy3_5ba-20p_v_long-bend-tgrb"
machine = "bessy3"
title = "BESSY 3 Design Kuske 5BA 20p Long Bend TGRB"
authors = ["Bettina Kuske"]
energy = 2500
simulations = ["elegant"]
labels = ["antibends", "combined function bends"]
description = """
5bend MBA lattice, 20 Perioden, langer Dipol mit transversem Gradienten und Gradienten 
im reverse bend, sprich versetzter Quadrupol
"""

[[lattices]]
namespace = "hwang"
name = "bessy3_4sexts_v_1"
machine = "bessy3"
title = "BESSY 3 Design Hwang 4 Sexts"
authors = ["Ji-Gwang Hwang"]
energy = 2500
labels = ["combined function bends"]
simulations = ["elegant", "madx"]
description = """
"""

[[lattices]]
namespace = "hwang"
name = "bessy3_5sexts_v_1"
machine = "bessy3"
title = "BESSY 3 Design Hwang 5 Sexts"
authors = ["Ji-Gwang Hwang"]
energy = 2500
simulations = ["elegant", "madx"]
labels = ["combined function bends"]
description = """
"""

[[lattices]]
namespace = "hzb"
name = "bessy2_stduser-2019-05-07-v_1"
machine = "bessy2"
title = "BESSY II Standard User 2019"
authors = ["HZB"]
energy = 1700
simulations = ["apace"]
labels = []
description = """
Standard User lattice of the BESSY II storage ring
(Here as reference and to test stuff!)
"""


[[lattices]]
namespace = "hzb"
name = "bessy2_design-1996_v_1"
machine = "bessy2"
title = "BESSY II Design Lattice 1996"
authors = ["HZB"]
energy = 1700
simulations = ["apace"]
labels = []
description = """
Fully symmetric Design Lattice of the BESSY II storage ring
(Here as reference and to test stuff!)
"""
